[[constraint]]
  name = "github.com/miekg/dns"
  version = "1.1.1"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "gopkg.in/alecthomas/kingpin.v2"
  version = "2.2.6"

[prune]
  go-tests = true
  unused-packages = true
